### ISSUE TITLE
Proposed sDEFI Index Synth weighting

### ISSUE THREAD

**Issue by garthtravers** [Synthetixio/synthetix#299]
<img width="825" alt="sDEFI weighting" src="https://user-images.githubusercontent.com/39815229/67916470-e5a10e80-fbe9-11e9-8d12-fe446c222640.png">

Here is the proposed sDEFI Index Synth weighting, determined according to current (31/10/2019) market caps. Please indicate support or rejection of this weighting using the emoji reactions.

**Comment by Arthur0x** [comment]
Thanks for sharing the table @garthtravers 

I am against giving Chainlink such a high weightage for a DEFI index since it's debatable whether they should be considered as DeFi in the first place.

Chainlink belongs to Oracle category which is a much broader and cover use-cases beyond just DeFi although the focal point is on DeFi at the moment.

Chainlink also have its own idiosyncratic catalyst (4chan meme and LINK Marines)and price movement that are not related to DeFi and will likely distort the value of the DEFI index.

This kind of defeat the purpose of giving people an opportunity to have exposure to DeFi sector in the first place, as 40% of the index is an oracle project which is not conclusively a DeFi project.

I am very critical of the DEFI index created by NASDAQ which include Amoveo with a 20% weightage! This is a perfect example of poor index construction. We should strive to create an index that's much more representative of the DeFi sector.

I propose to reduce the weightage of LINK to be on par with MKR and bump up the weightage of other DeFi projects token proportionally.

Proposed Weightage

Project | Weightage
LINK | 25.00%
MKR | 25.00%
ZRX | 13.00%
SNX | 13.00%
REN | 6.00%
LRC | 6.00%
KNC | 6.00%
BNT | 3.50%
MLN | 2.50%

**Comment by Arthur0x** [comment]
I am fine for LINK to be included in sDEFI index since they do have a lot of touch point with DeFi but oracle cover much broader use cases than DeFi. 

My main issue is over-representation of LINK in the DEFI token therefore making its value proposition moot. We have the chance to construct the first robust DeFi index and we shouldn't squander this opportunity.

I disagree with the final statement as for people who are bearish on DeFi as a whole (Bitcoin Maximalists, Marmot Boi etc), They should gain more for owning the inverse DEFI token since DeFi projects with lower market cap usually exhibit higher volatility on downside and go down in value faster and more furious.

**Comment by peterjmarko** [comment]
I am against this weighting.

I wasn't around when initial discussions and voting took place, so perhaps it's not fair for me to vote and comment this late in the game. However, I feel that putting together an index such as sDEFI needs a lot more input, thought and time. First of all, we need to define DeFi, and which coins qualify for inclusion at all. If the definition of DeFi can be pinned down, the next question is: do only 100% DeFi coins qualify, or do we accept anything over 50%? How do we determine the percentage? Is market cap the right metric for weight? How many coins to include in this index? Etc.

If these discussions have already taken place, then please point me to a summary of questions, answers and conclusions. All I can see is Twitter polls, which is a good start but not a methodology that can be defended.

The number of coins needs to be much greater than 9. From a statistical perspective, 30 components are needed for representative sampling. I'm not an expert on the DeFi space, but looking at the following lists makes me think that constructing an index using 30 coins should be easy.

https://defipulse.com/defi-list/
https://defirate.com
https://media.consensys.net/the-100-projects-pioneering-decentralized-finance-717478ddcdf2
https://www.block123.com/en/feature/awesome-ethereum-defi-decentralized-finance-list

Overall, I don't see that definitions, metrics, sources of information, etc., have been thoughtfully developed. 

On the other hand, I'm sure there is a lot of work being done that I'm not aware of, so it's possible that I'm off with my judgment. I'm happy to change my vote if you can inform me of discussions covering the above.

**Comment by hughkarp** [comment]
I'm clearly biased but no love for NXM (Nexus Mutual)?
You can even use our bonding curve as the price "oracle"
mcap is in the order of $10m

**Comment by kaiynne** [comment]
> The number of coins needs to be much greater than 9. From a statistical perspective, 30 components are needed for representative sampling. I'm not an expert on the DeFi space, but looking at the following lists makes me think that constructing an index using 30 coins should be easy.
> 
> https://defipulse.com/defi-list/
> https://defirate.com
> https://media.consensys.net/the-100-projects-pioneering-decentralized-finance-717478ddcdf2
> https://www.block123.com/en/feature/awesome-ethereum-defi-decentralized-finance-list

I don't want to be overly critical but it is hard to take this view seriously when there are not even 30 defi projects with tokens. I understand the argument for a larger sample size, but this is what we have to work with. It was unfortunate that REP did not make it in. But the point of the polls was to ideally see which assets people were interested in having exposure to and leveraging those communities.

The other consideration is price feeds and liquidity for any assets that are included, we need to be able to get a price feed with multiple sources which means we need a number of different exchanges. As you go further down the long tail of assets it becomes progressively harder, and their weighting would need to be so tiny as to not materially impact the index itself.

**Comment by peterjmarko** [comment]
Personally I think basing an index on 9 components is foolish. Look at:

S&P 500: 500 components
DJIA: 30 components
NASDAQ Composite: 3,300 components
Russell 2000: 2,000 components
Euro Stoxx 50: 50 components
FTSE 100: 100 components
CAC 40: 40 components
DAX 30: 30 components
Nikkei 225: 225 components
CSI 300: 300 components
etc.

If we cannot identify 30 solid DeFi coins, perhaps sDEFI is premature. It will not be much of an index, and will depend too much on a couple of coins. 

For Synthetix to create an index, there is a need for a solid data source, and not just price and market cap. Then a set of criteria needs to be developed for inclusion in index. Cannot be subjective. Then an algorithm for weighting. Cannot be guesswork. I don't see any of that. 

I would invite all to read this (if not already familiar with the story): https://www.thebalance.com/understanding-the-dow-jones-industrial-average-djia-357912

This is a small basket of 30 stocks, and there is a long history behind it, with some lessons learnt. 

"The original twelve stocks in the Dow Jones Industrial Average consisted almost entirely of commodity-based firms... In 1916, the Dow Jones Industrial Average was updated to include 20 stocks (known as “components”). By 1928, the DJIA was expanded to 30 stocks, which continues to be the rule today."

Notice the progression from 12 (1885) to 20 (1916) to 30 (1928). So the number of components was changed twice in 43 years but has remained constant for the past 91 years.

Original calculation of the index: "The process for calculating the reported figures for these new indices was the same: He added up the stock price of the companies he had chosen, divided by the number of companies in the index at the time, and published the result."

Flaws with this method: "The practical effect of this calculation was that a stock with a $100 share price would have five times the influence on the DJIA as one with a $20 share price (okay, not exactly, but you get the idea), even if the latter company had a market capitalization that was ten times as large. That’s why a company such as Berkshire Hathaway, which regularly trades at over $100,000 per share, couldn’t be added to the Dow without some sort of modification in the formula because it would instantly represent the entire index."

There is a specific problem with stock splits, which modify the price but not the fundamentals. The current fix is as follows: "To compensate, the divisor of the DJIA is frequently modified for corporate events and transactions. Long story short, in the event of a stock split, the value of the Dow Jones Industrial Average is calculated both before and after the split. The post-split divisor is modified so that a change in the stock price of the company results in the same percentage change in the overall index as if the split had never happened."

Referring to the above issues: "That is why you will often find professional money managers who instead use the S&P 500, which adjusts for overall market capitalization."

It's hard to believe but they still haven't fixed the DJIA.

Next up is the S&P 500: https://www.thebalance.com/what-is-the-sandp-500-3305888

Please read how the index is weighted and what the selection criteria for inclusion are. It's very far from haphazard or subjective. I bet not many knew here that DJIA tracks price and S&P 500 tracks market cap. It should be quite obvious which is the better method. 

So at the risk of boring you to death, were topics such as the above ever discussed re sDEFI? Were questions, answers and conclusions documented?

**Comment by peterjmarko** [comment]
> But the point of the polls was to ideally see which assets people were interested in having exposure to and leveraging those communities.

And here is the problem. A proper index is not created based on an opinion poll. In this case, the sDEFI index is supposed to be representative of the DeFi space. What are the metrics defining this space? What is your definition of DeFi? What qualifies to be called DeFi? Assuming that you can come up with a strict definition, what's the minimum DeFi content percentage for a coin to be included? Should it be, for example, Degree 1 or 4 DeFi as a minimum (according to this definition: https://blockgeeks.com/guides/demystifying-defi-ultimate-guide-2019/)? What is the minimum market cap? Minimum liquidity? Minimum number of exchanges it's listed on? Geographic coverage? Number of trading pairs? Minimum age? Is there a difference between lending platforms and exchanges? Should stablecoins be included? Etc, etc...

So if you don't see you have a problem here, it's really a waste of my time trying to explain it.

**Comment by peterjmarko** [comment]
> The other consideration is price feeds and liquidity for any assets that are included, we need to be able to get a price feed with multiple sources which means we need a number of different exchanges.

This is a valid point of course. Once again though, will you base your decisions on gut feel, or will there be a spec sheet for sDEFI?

**Comment by kaiynne** [comment]
> So if you don't see you have a problem here, it's really a waste of my time trying to explain it.

I think you are coming at this from a strange angle to be honest. You want some some kind rigid framework for inclusion, but that is just not possible in the current market. There are only 10-15 tokens that represent DeFi projects, many don't have tokens, Compound and dYdX being just two examples.

The reality is that any construction is going to be 'somewhat' arbitrary, but that does not mean there is no value in creating an index. The idea that it must be perfect or is worthless is simply wrong. There is value even in an imperfectly representative basket of DeFi projects, especially given that everyone is able to exercise their own discretion as to whether they want to hold it.

I suppose I most take issue with the fact that you are criticising the construction without putting forward any viable suggestions for improvement. But I definitely curious as to what your ideal index would look like? What assets would be included?

>What is the minimum market cap? Minimum liquidity? Minimum number of exchanges it's listed on? Geographic coverage? Number of trading pairs? Minimum age?

Again it appears you want a rigid framework for exclusion here, and that is simply not possible for a number of reasons. But to just highlight one critical one. We need to have multiple feeds to ensure that we can medianise the prices, so we need at least three at a minimum exchanges with reasonable liquidity. This unfortunately puts us in a position where we need to exercise judgement, because if you look at something like say Electroneum you might think it is actually fine to include, it has multiple exchanges and 100k USD of volume per day, but the issue is that the majority of that volume comes from exchanges that are not that reputable. So you if you used a rigid framework you could easily end up with a false positive.

Final point, why would we include stablecoins in the basket? I'm really confused by that suggestion.

**Comment by Arthur0x** [comment]
> 
> 
> I'm clearly biased but no love for NXM (Nexus Mutual)?
> You can even use our bonding curve as the price "oracle"
> mcap is in the order of $10m

Unfortunately NXM was not included in the voting round for DeFi Synths last time, wasn't aware there's a market price for NXM due to lack of exchange listing.

**Comment by mikedemarais** [comment]
adding UNI-V1:DAI to index should be considered

**Comment by CryptoToit** [comment]
1) I don't "mind" $LINK being included as they are focused on helping build and support the decentralised crypto space. But the main question is are they themselves not a fully centralised project?

2) I like the idea from Mike to consider UNI:-V1:DAI  :)

**Comment by cryptic-prophet** [comment]
Here is an example of sDEFI composition using 27 coins. This is just an example, and the only criteria for inclusion in the list was a minimum $1 million market cap. Weighting is capped market cap, method 2. A complete methodology would include many more factors. 

Since there seems to be a rush to go ahead with a half-baked product, I just wanted to show quickly that it is possible to have a much larger set. All coins can (and should) be questioned. For example, is ETH a DeFi coin? Yes and no - how will you come to a definitive answer?

The point I am trying to make is that one first needs to develop a product framework so that inclusion/exclusion can be defended. There are many more parts to proper product design: objective, eligibility criteria, methodology, and maintenance - to mention just the main considerations. I don't believe most of these have been taken into account. As a minimum, a product fact sheet would be created and posted for discussion.

For these reasons, it is my view that launching sDEFI based on the proposals above is premature. 

<img width="384" alt="sDEFI composition example" src="https://user-images.githubusercontent.com/57357164/68129715-08803b00-fee8-11e9-8617-b377069b3715.png">

**Comment by cryptic-prophet** [comment]
Link to the table above: https://docs.google.com/spreadsheets/d/1QYcxtgrkO8MmHtM5VBOIxrutAETHbxhpI0i4TeQZks4/edit?usp=sharing

**Comment by cryptic-prophet** [comment]
Here is an updated table showing the two capped MC methods for calculating weights. The point is not the list of coins but the weighting methods.

<img width="493" alt="sDEFI_example_2" src="https://user-images.githubusercontent.com/57357164/68213005-beab5980-ffa8-11e9-84e0-c414a443010b.png">

**Comment by cryptic-prophet** [comment]
And here is one with ETH, stablecoins and wrapped coins removed. Minimum market cap for this list is $20 million. [EDIT: Method 2 numbers updated after remembering to run Solver! :)]

<img width="517" alt="sDEFI_example_3" src="https://user-images.githubusercontent.com/57357164/68215030-8ad23300-ffac-11e9-80a3-c071b3fe30f9.png">

**Comment by sdchetty** [comment]
Honest questions;

1. Why is LINK being included and given such a strong weighting when it's use case extends much further than just DeFi? It feels like the odd one out, I get that they're supporting the platform but that should be divorced from this decision.

2. Why are there more coins included in sDEFI compared to iCEX? I don't see the point of including a long tail of liquidity platforms for an allocation of less than 5% that barely have adoption. If you go on DeFipulse/State of the dApps it clearly shows the leading DeFi protocols/platforms - why not just include those that are actually being used by people? It would make more sense to just simplify it and go for a Top 5 of MKR, SNX, REN, KNC, BNT. Once things like REP & MLN start gaining traction then yeah revise the composition by all means but at this stage it's still too early to include them.

Not a criticism at all, I'm really looking forward to this index, just want to make sure it reflects current state.

**Comment by Rjrunner44** [comment]
RUNE should prob be added

**Comment by justinjmoses** [comment]
Sorry @Rjrunner44 but this conversation is now closed. At some future point we can vote on a new sDEFI index (or have multiple).
