### ISSUE TITLE
Multiple race conditions with asset pricing in exchange and other issues

### ISSUE THREAD

**Issue by robertsdotpm** [Synthetixio/synthetix#664]
Hello everyone, I was tasked to review the Synthetix white paper recently for issues. I also briefly looked at the code for problems and I've noticed some issues that I'd like to bring up. Keep in mind I may be mistaken about some of this.

## 1. Prices aren't used.

In the exchange dapp the user receives a quote for the underlying asset from ChainLink. If the user agrees with the price they may choose to 'mint' a new synthetic asset that will represent their sUSD purchase quantity of the external price of the asset.

Unfortunately, there is no price parameter for the dapp calls that handle this minting / issuing which means the price of the external asset can change in-between the time that the user is shown the quote and the time they submit the call to the dapp. Essentially, the user has no idea what price they end up 'paying' for a synthetic (and I use the term paying here very loosely given how Synthetix works.)

As you can imagine: this is a massive flaw in the design of the software. If prices aren't used it obviously bypasses the circuit breaker too -- since from a user's perspective the % changes from what they saw could be anything. What would mitigate the impact of this for this particular code is the way prices are broken up into their current time periods. But that does not fix the problem as users still could end up submitting orders in-between updates from the pricing oracles which would cause a race condition for which price they ended up using.

Similar to the above issue: the UI also contains code where it fetches external prices multiple times. This can result in seeing gas estimations that no longer apply. Prices that no longer exist...

https://github.com/Synthetixio/synthetix/blob/4fd3c1e6ac849f8c43277493e636a2ecc63801e0/contracts/Exchanger.sol#L198

https://github.com/Synthetixio/synthetix-exchange/blob/master/src/pages/Trade/components/CreateOrderCard/CreateOrderCard.js#L266

## 2. Exchange rates can be stale by multiple hours.

The contract code includes a 'timestamp' check for the freshness of price quotes. The current freshness parameter is set to 3 hours which is a remarkably long time for a market to rely on information for. Wall street firms have been known to spend millions just to reduce a few milliseconds in trading time... Obviously that is not on the menu here, but 3 hours seems like a very odd choice to me.

https://github.com/Synthetixio/synthetix/blob/4fd3c1e6ac849f8c43277493e636a2ecc63801e0/contracts/ExchangeRates.sol#L42

## 3. Error hiding.

The exchange rate code contains logic to hide errors in balance checks that could potentially result in traders losing money with coding or input errors. The code in question checks their remaining balance after settlement to see if they have enough to cover an exchange. But if they don't it simply sets the exchange amount to their remaining balance.

https://github.com/Synthetixio/synthetix/blob/6125f587a7e6c22989e1a239ed3d3932bce79fcf/contracts/Exchanger.sol#L271

## 4. Backdoors

Most aspects of the exchanges behaviour can be controlled by the owner. For example, the owner can change the amount of time that a price is considered 'fresh for' to zero and cause every trade to fail. Or they can hijack price feeds directly and set them to anything they like:

```solidity
function setOracle(address _oracle) external onlyOwner {
    oracle = _oracle;
    emit OracleUpdated(oracle);
}
```

I believe it's in bad taste not to inform users the level of centralisation in this project. Given that one would assume that contracts on the blockchain cannot be changed once they're made and owners here can change almost everything...

https://github.com/Synthetixio/synthetix/blob/6125f587a7e6c22989e1a239ed3d3932bce79fcf/contracts/SystemSettings.sol#L193

# 5. Odd pricing edge-case code?

I have not looked at this too closely but the pricing code and the way it's broken up into time-periods looks scary. Particularly the lines that seem to check for 'accidental' over-allocations? What is happening here? 

https://github.com/Synthetixio/synthetix/blob/6125f587a7e6c22989e1a239ed3d3932bce79fcf/contracts/Exchanger.sol#L191

**Comment by justinjmoses** [comment]
Hi @robertsdotpm, great to see you're doing a deep dive on our code. Let me address each of your points in turn. 

Just one minor note before I begin, the code in `develop`, the default branch, is not what's yet on mainnet. It gets promoted during a release to `master` where it reflects what's on mainnet. We're working on better bridges between what's in GitHub to what's verified in Etherscan. We're looking at using https://github.com/ethereum/sourcify - not sure if you have any thoughts on this?

Also, most of our technical discussion goes on in the [`#dev-portal`](https://discord.gg/DSgQRHG) channel in our discord. Beyond the core contributors, there are many developers active in the Synthetix community who have deep insight into the project and the history. There are also Guardians in Discord - moderators and super-users of the protocol who can help answer questions and point you in the right direction as you're doing your research.

Finally, you'll see I've referenced many [Synthetix Improvement Proposals - SIPs](https://sips.synthetix.io/all-sip). These detail the changes that the protocol have undergone since it pivoted from Havven to Synthetix, in December 2018 (this was `v2`). The detail of these changes are important, as they explain the context within which the protocol has evolved. Understanding these will better help you understand the code as it is. There are too many to list, but those I've linked below are critical to understand when reading the Synthetix codebase.

## 1. Prices aren't used

When you exchange in Synthetix, you are basically repricing debt that is in the form of a synthetic asset. Your transaction to exchange effectively says - take 100% of the synth I have and denominate it in that of the one I want, subtracting an exchange fee. You're right in that the [`exchange` function](https://docs.synthetix.io/contracts/source/contracts/synthetix/#exchange) doesn't take a price argument or a slippage param. It's something that's been discussed in Discord, additional arguments for `price` and `slippage` to tackle the scenario you mention. Anyone in the community is welcome to create a SIP to propose adding this feature: https://github.com/Synthetixio/SIPs/pulls - please feel free to submit one. Though it's typically a good idea to discuss first with others in discord to get an idea of how much support there will be to have it successfully voted on.

## 2. Stale rates

Rates are pushed in from external sources into the Synthetix `ExchangeRates` contract via the centralized oracle and various Chainlink `Aggregator` contracts periodically via a decentralized network of nodes, typically when the off-chain processes watching price changes detect a variation at or above some amount. For example, the XAG-USD Chainlink Aggregator will update whenever that change is 1% or above: https://feeds.chain.link/xag-usd. The Synthetix oracle has a much lower threshold of between 0.3-0.5%, depending on the asset. 

> Note: as part of the upcoming release at the end of August (entitled *Pollux*), Synthetix is planning on migrating away from its centralized oracle altogether, and rely on Chainlink's decentralized networks completely. See https://sips.synthetix.io/sips/sip-36.

Because rates are pushed into the protocol, and because it's a process that could fail in some way, there needs to be some mechanism to ensure that the rate is fresh - hence stale rates (in Chainlink terms, it's referred to a heartbeat, see link above for XAG). Obviously, the deviation threshold is not always enough to capture changes to prices, particularly for assets that have less volatility, like forex prices. In those cases, the heartbeat ensures that the oracle is still correctly working - it's a kind of dead man switch - letting the protocol know that nothing has gone awry with the offchain process of pushing prices. And, because pushing prices costs Ether in the form of gas, the frequency with which they are pushed - particularly when it's in the form of a heartbeat - is something that we'd try to lower, to reduce excess cost of the oracle networks. 

The current 3 hours of the heartbeat is something the protocol has been using since inception (even as Havven, an oracle was required to determine the fair market value of `HAV` in order to issue the stablecoin), and it was determined fairly arbitrarily based on the cost of running the oracle combined with the potential impact of staleness on the protocol. 

It's definitely an active area of research - the need for the heartbeat or rather a kind of dead man switch without a price - and it's something the Chainlink team and Synthetix are discussing going forward.  

## 3. Error hiding

I think you misunderstood that particular piece of code. It's admittedly not easy to read the Synthetix codebase and infer the current state because as we've iterated on contracts and yet continued to work around deployed legacy state and proxy contracts, the code can be difficult to read without any historical context. 

That particular piece of code - `Exchanger.calculateAmountAfterSettlement()` - is used within Fee Reclamation (which is a whole other story and worth reading and understanding: https://sips.synthetix.io/sips/sip-37). But in essence, when a user tries to exchange some amount of `src` synth, let's say `100 sUSD` into `sETH`, if they owe anything from a previous unsettled exchange into `sUSD` from some other synth whose price changed during the waiting period, then that amount is deducted from their `100` amount and that is the amount that is settled. I do recommend you read through Fee Reclamation fully to understand the problem with oracle frontrunning and how settlement solves it, albeit at the cost of composibility. 

## 4. Backdoors

Synthetix has always had centralization risk in the form of owner functions, and this is something the core contributors and community have been very aware of (there are numerous articles out there on this). Because it's something everyone has known for so long, perhaps those of us in the community haven't done a better job of highlighting this continued risk. However, our blog has mentioned the issue numerous times, most recently via https://blog.synthetix.io/synthetix-foundation-decommissioned and it's mentioned in the docs: https://docs.synthetix.io/integrations/guide/#proxies. I do take it that it could be highlighted more fully. You are welcome to submit a PR into the docs repo if you feel a specific page or section should be highlighted more: https://github.com/Synthetixio/synthetix-docs/

The core contributors of Synthetix are razor focused on decentralizing and removing even the protocolDAO `onlyOwner` functions. After the release this month where the remainder of the ExchangeRates prices will be migrated to Chainlink aggregators and the `setOracle` function will be defunct, the plan is to move to a `DelegatedMigrator` contract which will own everything except the SCCP-configurable settings from `SystemSettings` (separated for brevity of performing SCCP changes) and this contract will be the owner of all of Synthetix going forward. With the `DelegatedMigrator` all changes will need to be performed by an on-chain migration contract, and the SNX stakers will be able to reject protocol changes in proportion to the debt they hold. For more information, here is the PR of the SIP: https://github.com/Synthetixio/SIPs/pull/127/files 

## 5. Odd-pricing edge cases

[SIP-65](https://sips.synthetix.io/sips/sip-65) is about protecting the system from invalid prices posted on-chain. If the Synthetix oracle or any Chainlink Aggregator mistakenly posts a price on-chain that is grossly invalid (such as `0` or some other `uint` that isn't correct), SIP-65 ensures that this action triggers a pause of the synth in question. The particular line of code you referenced states that in the edge-case of a settlement around a price spike, then because the settlement is due to an event in the past (at least `waitingPeriodSecs` ago, but likely much more), we cannot execute the spike, and we cannot treat the settlement reclaim or rebate as valid, so in that case, the contract allows the trade to be settled with `0` rebate and `0` reclaim. If you read SIP-65 in detail, you'll see a discussion about this particular edge-case.

**Comment by robertsdotpm** [comment]
That's a very good in-depth reply. I'm glad the team is aware of these issues. That changes my perspective of the project and makes me much more confident in the project. +1
